### ISSUE TITLE
install.py should not indent example config.py

### ISSUE THREAD

**Issue by nhnb** [postsai/postsai#44]
When `install.py` is invoked before a configuration file has been created, it outputs an example configuration file. This output is indent by four spaces to help people identify this sample code.

This indent, however, prevents simple copy & pasting because Python does not like it:

~~~~
Traceback (most recent call last):
  File "./install.py", line 7, in <module>
    import api
  File "/var/www/postsai/api.py", line 12, in <module>
    import config
  File "/var/www/postsai/config.py", line 3
    db = {
    ^
~~~~

`install.py` should not use an indent.

**Comment by nhnb** [comment]
Fixed in 0.9.0
